service: SwitchCheckService
provider:
    name: aws
    runtime: node4.3
    iamRoleStatements:
      - Efect: Allow
        Action:
          - cloudwatch: *
        Resource: '*'
package:
  exclude:
    - jsconfig.json
    - event-samples
    - package.json
    - node_modules/**
    - '!node_modules/aws-sdk/**'

functions:
  switchCheckFunction:
    handler: switch.check
    events:
      - schedule: cron(0/10 * * * ? *)
