service: SwitchCheckService

provider:
    name: aws
    runtime: nodejs4.3
    stage: prod
    region: ap-northeast-1

package:
  exclude:
    - event-samples
    - package.json
    - node_modules/**
    - '!node_modules/aws-sdk/**'
    - '!node_modules/cheerio-httpcli/**'

functions:
  switchCheckFunction:
    handler: switch.check
    events:
      - schedule: cron(0/1 10-18 * * ? *)
